services:
  # Backend Node.js - CENTER
  - type: web
    name: center-backend-nodejs
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: ./backend
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /api/server-info
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 7823
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_SECRET_KEY
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
    autoDeploy: true

